# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementboxcheckin',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='measurementboxcheckin',
            name='git_head',
            field=models.CharField(default='2222222222222222', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementboxcheckin',
            name='temp',
            field=models.DecimalField(decimal_places=1, default=99.9, max_digits=4),
            preserve_default=False,
        ),
    ]
