# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementboxcheckin',
            name='hostname',
            field=models.CharField(default='nully', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurementboxcheckin',
            name='choice_text',
            field=models.CharField(max_length=400),
        ),
    ]
