# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0002_auto_20160609_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementboxcheckin',
            name='id',
        ),
        migrations.AlterField(
            model_name='measurementboxcheckin',
            name='datetime',
            field=models.DateTimeField(primary_key=True, verbose_name=b'checkin time'),
        ),
        migrations.AlterField(
            model_name='measurementboxcheckin',
            name='hostname',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
