# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0003_measurementbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementbox',
            name='location',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
    ]
