# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0004_measurementbox_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementbox',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
