# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0005_auto_20160715_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementboxcheckin',
            name='uptime',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
