# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_box_monitor', '0006_measurementboxcheckin_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementboxcheckin',
            name='public_ip',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
